const $=s=>document.querySelector(s),h=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),uid=()=>Math.random().toString(36).slice(2,9);
const OFF="https://www.moderncoe.edu.in/",CH="ACM:acm-student-chapter-neww,ISLE:isle-student-chapter-new,PMA:pma-student-chapter-new,IEEE:ieee-student-chapter-new,CSI:csi-student-chapter-new,IETE:iete-student-chapter-new,IEI:iei-student-chapter-new,SAE:sae-student-chapter-new,IET:iet-student-chapter-new,S4DS:s4ds-student-chapter-new".split(",").map(s=>s.split(":")),
CL="FOSS:foss-club-new,Robotics:robotics-club-new,GraphiX:graphics-club-new,Cypher:cypher-club-new,Aero:aero-club-new,Brain Stormer's:brain-stormers-club-new,Wall Magazine (Foxcodes Campus):foxcodes-campus-club-new,Metamorph:metamorph-club-new,Pegasus:pegasus-club-new,Code Cooks:code-cooks-club-new,Technofuel:technofuel-club-new,Art Glimpse:art-glimpse-club-new,CoDE Club (AIML):code-club-new,CoDE Club (AIDS):code-club-aids-new,PIXINSIGHT:pixinsight-club-new,App Club:app-club-new,Rotaract Club ENTC:rotaract-club-new,Mars Club:mars-club-new,Astronomy Club:-astronomy-club-new".split(",").map(s=>s.split(":")),
AC="SPDC Centre:spdc-centre-new,ED Cell:ed-cell-new,NSS:nss-new,M-Pulse:m-pulse-new,Art Circle:art-circle-new,Sports:sports-new,Student Welfare:student-welfare-new,ISR:isr-new,Karmanya:-pes-karmanya".split(",").map(s=>s.split(":")),
DEPTS=["Computer","IT","E&TC","Mechanical","Electrical","Electronics & Computer","MCA","MBA","AI&DS","AI&ML"],
DM={ACM:"Computer",CSI:"Computer","App Club":"Computer",Aero:"Mechanical",SAE:"Mechanical",IEEE:"E&TC",IETE:"E&TC","Rotaract Club ENTC":"E&TC","CoDE Club (AIML)":"AI&ML","CoDE Club (AIDS)":"AI&DS"};
const seed=()=>{const d={clubs:[...CH.map(([n,u])=>[n+' Student Chapter','Chapter',n,u]),...CL.map(([n,u])=>[n,'Club',n,u]),...AC.map(([n,u])=>[n,'Activity',n,u])].map(([name,type,k,u],i)=>({id:'c'+i,name,type,url:OFF+u,dept:DM[k]||'All',about:type=='Activity'?'Official MCOE activity. Members can add details from their workspace.':'Sample description. Club members can edit this from their workspace.'})),
users:[],me:null,reqs:[],regs:[],anns:[{id:'a1',cid:'c4',title:'CSI Club Interviews 2026: technical, design, event management, marketing, social media and documentation teams. Registration closes 5 Oct.',date:'2026-10-04'}],
events:[{id:'e0',cid:'c4',title:'CSI Club Interviews 2026 (5 to 6 Oct)',date:'2026-10-05',venue:'Room 325, 11:30 am to 12:30 pm',cap:100},{id:'e1',cid:'c0',title:'Intro to Git and GitHub (sample)',date:'2026-10-20',venue:'Venue to be announced',cap:60},{id:'e2',cid:'c11',title:'Robotics workshop (sample)',date:'2026-10-27',venue:'Venue to be announced',cap:30}]};
d.clubs[4].about='Think. Code. Innovate. Turn your ideas into impact with the Department of Computer Engineering.';return d};
let D;try{D=JSON.parse(localStorage.pulse2)}catch(e){}D=D||seed();D.fav=D.fav||[];
const save=()=>localStorage.pulse2=JSON.stringify(D),me=()=>D.users.find(u=>u.id==D.me),cn=id=>D.clubs.find(c=>c.id==id)?.name||'',left=e=>e.cap-D.regs.filter(r=>r.eid==e.id).length,own=c=>!!me()?.clubs?.includes(c),cid=()=>sessionStorage.cid;
const need=r=>{const u=me();if(!u||(r&&u.role!=r)){location='login.html';return}return u};
const toast=t=>{const d=document.createElement('div');d.className='toast';d.setAttribute('role','status');d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),2600)};
const TODAY=new Date(Date.now()-new Date().getTimezoneOffset()*6e4).toISOString().slice(0,10),dayDiff=d=>Math.round((new Date(d)-new Date(TODAY))/864e5),dayNum=d=>+d.slice(8,10),mon=d=>['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][+d.slice(5,7)-1],
cd=d=>{const n=dayDiff(d);return n<0?'<span class=chip>Ended</span>':n==0?'<span class="chip soon">Today</span>':n<4?`<span class="chip soon">In ${n} day${n>1?'s':''}</span>`:`<span class=chip>In ${n} days</span>`};
const nextEv=()=>{const e=[...D.events].filter(x=>dayDiff(x.date)>=0).sort((a,b)=>a.date<b.date?-1:1)[0];return e?`<section class=next><div><small>Happening next</small><h3>${h(e.title)}</h3><p class=cnt>📅 ${h(e.date)} &nbsp; 📍 ${h(e.venue)} &nbsp; ${cd(e.date)}</p></div><a class=btn href="events.html">Register now</a></section>`:''};
const CAT={Tech:['FOSS','Cypher','Code Cooks','CoDE Club (AIML)','CoDE Club (AIDS)','App Club','PIXINSIGHT'],Build:['Robotics','Aero','Technofuel','Mars Club','Metamorph','Astronomy Club'],Create:['GraphiX','Wall Magazine (Foxcodes Campus)','Pegasus'],Cultural:['Art Glimpse','Art Circle','M-Pulse','Karmanya'],Sports:['Sports'],Professional:['ED Cell','SPDC Centre']},
EM={Tech:'💻',Build:'🛠️',Create:'🎨',Cultural:'🎭',Sports:'⚽',Community:'🤝',Professional:'🎓'},CC={Tech:'#6D4AFF',Build:'#FF8A3D',Create:'#FF5C7A',Cultural:'#C13BFF',Sports:'#0FA3B1',Community:'#19B394',Professional:'#2F7BFF'},
catOf=c=>c.type=='Chapter'?'Professional':Object.keys(CAT).find(k=>CAT[k].includes(c.name))||'Community',RM=matchMedia('(prefers-reduced-motion:reduce)').matches;
const QZ=[{q:'Free Saturday. What are you doing?',o:[['💻 Hacking on a side project','Tech'],['🛠️ Building something that moves','Build'],['🎨 Designing or writing','Create'],['🎭 Performing or making art','Cultural'],['🏅 Playing a sport','Sports'],['🤝 Running a drive or event','Community']]},
{q:'How do you like to work?',o:[['🎧 Solo, headphones on','Tech,Create'],['👥 Small squad, shared goal','Build,Tech'],['📣 Big crowd, big energy','Community,Cultural']]},
{q:'What do you want from a club?',o:[['📈 A career edge','Professional,Tech'],['🧪 Hands-on skills','Build,Tech'],['✨ A creative outlet','Create,Cultural'],['🌱 To make an impact','Community']]}];
let Q={s:0,a:[]},CF='All';
const quiz=()=>{if(Q.s<QZ.length){const z=QZ[Q.s];return `<div class=dots>${QZ.map((_,i)=>`<i class="${i<=Q.s?'on':''}"></i>`).join('')}</div><p class=qh>Not sure where to start? Answer 3 quick questions.</p><h2>${z.q}</h2><div class=opts>${z.o.map((o,i)=>`<button data-a=qz data-i=${i}>${o[0]}</button>`).join('')}</div>`}
const n={};Q.a.forEach(x=>n[x]=(n[x]||0)+1);const top=Object.keys(n).sort((a,b)=>n[b]-n[a])[0]||'Tech',pk=D.clubs.filter(c=>catOf(c)==top).slice(0,4);
return `<h2>${EM[top]} You would fit right in with ${top}</h2><p>Sample matches based on your answers:</p><div>${pk.map(c=>`<a class=pick href="clubs.html?q=${encodeURIComponent(c.name)}">${h(c.name)}</a>`).join('')}</div><p><button class=ghost data-a=qr>Start over</button></p>`};
const applyF=()=>{const f=$('#flt');if(!f)return;const v=new FormData(f),s=(v.get('q')||'').toLowerCase(),d=v.get('d');let n=0;document.querySelectorAll('#cg .card').forEach(c=>{const ok=c.dataset.n.includes(s)&&(CF=='All'||(CF=='Saved'?D.fav.includes(c.dataset.id):c.dataset.c==CF))&&(!d||c.dataset.d==d||c.dataset.d=='All');c.hidden=!ok;n+=ok});document.querySelectorAll('#chips button').forEach(b=>b.classList.toggle('on',b.dataset.i==CF));$('#cnt2').textContent=n?`Showing ${n} of ${D.clubs.length}`:'No matches. Try a shorter search or another category.'};
const evCard=(e,act)=>{const u=me(),r=u&&D.regs.find(r=>r.eid==e.id&&r.uid==u.id),l=left(e),k=catOf(D.clubs.find(c=>c.id==e.cid)||{name:'',type:''}),tk=e.cap-l;return `<article class=card style="--cc:${CC[k]}"><div class=top><span>${EM[k]}</span><div class=dt><b>${dayNum(e.date)}</b><span>${mon(e.date)}</span></div></div><small>${h(cn(e.cid))}</small><h3>${h(e.title)}</h3><p class=r>📍 ${h(e.venue)}</p><div class=bar role=img aria-label="${tk} of ${e.cap} seats taken"><i style="width:${Math.min(100,tk/e.cap*100)}%"></i></div><p class="r m">${tk} going, ${l} seats left</p>${cd(e.date)}${act?(r?`<button class=ghost data-a=unreg data-c="Cancel this registration?" data-i=${e.id}>Cancel registration</button>`:`<button data-a=reg data-i=${e.id} ${l<1?'disabled':''}>${l<1?'Full':"I'm in! Register"}</button>`):''}</article>`};
const clubCard=c=>{const u=me(),rq=u&&D.reqs.find(r=>r.cid==c.id&&r.uid==u.id),k=catOf(c),on=D.fav.includes(c.id),b=own(c.id)?'<span class=tag>Your club</span>':rq?`<span class=tag>${{ok:'Joined',no:'Declined',wait:'Request sent'}[rq.st]}</span>`:`<button data-a=join data-i=${c.id}>Request to join</button>`;
return `<article class=card data-n="${h(c.name.toLowerCase())}" data-id=${c.id} data-c=${k} data-d="${h(c.dept)}" style="--cc:${CC[k]}"><div class=top><span>${EM[k]}</span><span class=tag>${k}</span></div><button class="fav${on?' on':''}" data-a=fav data-i=${c.id} aria-pressed=${on} aria-label="Save ${h(c.name)}">♥</button><h3>${h(c.name)}</h3><p>${h(c.about)}</p><p class=m>${c.dept=='All'?'Open to all departments':h(c.dept)}</p><a class=off href="${c.url}" target=_blank rel=noopener>Official page ↗</a>${b}</article>`};
const studs=c=>{const m=new Map();D.reqs.filter(r=>r.cid==c).forEach(r=>{const u=D.users.find(x=>x.id==r.uid);if(u)m.set(u.id,{u,st:{ok:'Joined',wait:'Pending',no:'Declined'}[r.st],n:0})});const ids=D.events.filter(e=>e.cid==c).map(e=>e.id);D.regs.filter(r=>ids.includes(r.eid)).forEach(r=>{const u=D.users.find(x=>x.id==r.uid);if(!u)return;if(!m.has(u.id))m.set(u.id,{u,st:'Event only',n:0});m.get(u.id).n++});return[...m.values()]};
const regList=e=>{const L=D.regs.filter(r=>r.eid==e.id).map(r=>D.users.find(x=>x.id==r.uid)).filter(Boolean);return `<details><summary>Registered students (${L.length})</summary>${L.length?'<ol>'+L.map(u=>`<li>${h(u.name)}, ${h(u.email)}</li>`).join('')+'</ol>':'<span class=m>No registrations yet.</span>'}</details>`};
const P={
home(){const names=D.clubs.map(c=>`<span>★ ${h(c.name)}</span>`).join('');
$('#m').innerHTML=`<section class=hero>${[['💻',62,6,0,30],['🎨',80,26,-1.5,44],['🤖',68,50,-3,36],['📸',88,62,-2,50],['🎸',56,74,-4,28],['🚀',90,4,-.8,40]].map(([i,l,t,d,s])=>`<span class=bub data-s=${s} style="left:${l}%;top:${t}%;animation-delay:${d}s" aria-hidden=true>${i}</span>`).join('')}<h1>Find the crew where you <span id=tw class=sw>code</span>.</h1><p class=sub>Every MCOE club, chapter and event in one place. Be more than a student.</p><form id=q class=search><input name=q placeholder="Search clubs, like Robotics or ACM" aria-label="Search clubs"><button>Search</button></form><p class=hint>Tip: press / anywhere to search.</p></section><div class=mq aria-hidden=true><div>${names}${names}</div></div>${nextEv()}<section class=quiz>${quiz()}</section>
<section class=stats>${[[D.clubs.length,'chapters, clubs and activities'],[D.events.length,'events coming up'],[D.users.length,'students signed up']].map(([n,l])=>`<div><b data-cu=${n}>0</b>${l}</div>`).join('')}</section>
<h2>Coming up</h2><div class=grid>${D.events.slice(0,3).map(e=>evCard(e)).join('')}</div>
<h2>Announcements</h2><div class=list>${D.anns.slice(0,4).map(a=>`<p><b>${h(a.title)}</b><span class=m>${h(cn(a.cid))}, ${h(a.date)}</span></p>`).join('')}</div>`;
document.querySelectorAll('[data-cu]').forEach(el=>{const to=+el.dataset.cu;if(RM){el.textContent=to;return}let n=0;const iv=setInterval(()=>{n=Math.min(to,n+Math.ceil(to/18));el.textContent=n;if(n>=to)clearInterval(iv)},45)})},
clubs(q){$('#m').innerHTML=`<h1 style="font-size:clamp(34px,6vw,60px)">Clubs, chapters and activities</h1><form id=flt class=filters><input name=q value="${h(q.get('q')||'')}" placeholder="Search by name" aria-label=Search><select name=d aria-label=Department><option value="">All departments${DEPTS.map(x=>`<option>${h(x)}</option>`).join('')}</select></form><div class=chips id=chips>${['All',...Object.keys(EM),'Saved'].map(k=>`<button type=button data-a=cat data-i=${k}>${EM[k]||(k=='Saved'?'♥':'✨')} ${k}</button>`).join('')}</div><p class=m id=cnt2 aria-live=polite></p><div class=grid id=cg>${D.clubs.map(clubCard).join('')}</div>`;applyF()},
events(){$('#m').innerHTML=`<h1 style="font-size:clamp(36px,7vw,64px)">Events and programs</h1><div class=grid>${[...D.events].sort((a,b)=>a.date<b.date?-1:1).map(e=>evCard(e,1)).join('')||'<p class=empty>No events yet.</p>'}</div>`},
login(){$('#m').innerHTML=`<div class=auth><h2>Log in</h2><form id=login><label>Email<input name=email type=email required></label><label>Password<input name=pw type=password required></label><label class=pw><input type=checkbox id=sp>Show password</label><button>Log in</button></form>
<h2>New here? Create an account</h2><form id=signup><label>Name<input name=name required></label><label>Email<input name=email type=email required></label><label>Password (6 or more characters)<input name=pw type=password minlength=6 required></label><label>I am a<select name=role id=role><option value=student>Student<option value=member>Club member</select></label><label id=cl hidden>My club<select name=club>${D.clubs.map(c=>`<option value=${c.id}>${h(c.name)}`).join('')}</select></label><button>Create account</button></form></div>`;
$('#role').onchange=e=>$('#cl').hidden=e.target.value!='member';$('#sp').onchange=e=>document.querySelectorAll('#login [name=pw],#signup [name=pw]').forEach(i=>i.type=e.target.checked?'text':'password')},
me(){const u=need();if(!u)return;const R=D.reqs.filter(r=>r.uid==u.id),regs=D.regs.filter(r=>r.uid==u.id);
$('#m').innerHTML=`<h1 style="font-size:clamp(36px,7vw,64px)">Hi, ${h(u.name)}</h1><h2 class="strip torn" style="--c:var(--lav)">My clubs</h2><div class=list>${[...(u.clubs||[]).map(c=>[c,'Member']),...R.map(r=>[r.cid,{ok:'Joined',no:'Declined',wait:'Request pending'}[r.st]])].map(([c,s])=>`<p><b>${h(cn(c))}</b> <span class=tag style="--c:var(--blue)">${s}</span></p>`).join('')||'<p>You have not joined a club yet. <a href="clubs.html">Browse clubs</a></p>'}</div>
<h2 class="strip torn" style="--c:var(--yellow)">My registrations</h2><div class=grid>${regs.map(r=>{const e=D.events.find(x=>x.id==r.eid);return e?`<article class=card><small>${h(cn(e.cid))}</small><h3>${h(e.title)}</h3><p class=r>📅 ${h(e.date)}</p><p class=ticket>Ticket ${r.id.toUpperCase()}</p><button class=ghost data-a=unreg data-c="Cancel this registration?" data-i=${e.id}>Cancel registration</button></article>`:''}).join('')||'<p class=empty>No registrations yet. <a href="events.html">See events</a></p>'}</div>`},
club(){const u=need('member');if(!u)return;const cs=u.clubs;let c0=cid();if(!cs.includes(c0))c0=cs[0];sessionStorage.cid=c0;const c=D.clubs.find(x=>x.id==c0),ev=D.events.filter(e=>e.cid==c0),rq=D.reqs.filter(r=>r.cid==c0&&r.st=='wait'),S=studs(c0);
$('#m').innerHTML=`<h1 style="font-size:clamp(34px,6vw,60px)">${h(c.name)} workspace</h1>${cs.length>1?`<select id=sw aria-label="Switch club">${cs.map(x=>`<option value=${x} ${x==c0?'selected':''}>${h(cn(x))}`).join('')}</select>`:''}
<div class=cols><section><h2>Club profile</h2><form id=about><label>About<textarea name=about rows=4>${h(c.about)}</textarea></label><button>Save profile</button></form><h2>Post an announcement</h2><form id=anf><label>Title<input name=title required></label><button>Publish announcement</button></form></section>
<section><h2>Create an event</h2><form id=evf><label>Title<input name=title required></label><label>Date<input name=date type=date required></label><label>Venue<input name=venue required></label><label>Seats<input name=cap type=number min=1 value=50 required></label><button>Create event</button></form></section></div>
<h2 class="strip torn" style="--c:var(--mint)">Join requests</h2><div class=list>${rq.map(r=>`<p><b>${h(D.users.find(x=>x.id==r.uid)?.name)}</b> <button data-a=ok data-i=${r.uid}>Accept</button> <button class=ghost data-a=no data-i=${r.uid}>Decline</button></p>`).join('')||'<p>No pending requests.</p>'}</div>
<h2 class="strip torn" style="--c:var(--blue)">Students (${S.length})</h2><div class=list><p><input id=sf placeholder="Filter by name or email" aria-label="Filter students"> <button class=ghost data-a=csvs>Download students (CSV)</button></p>${S.length?`<div class=tw><table class=tbl><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Events</th></tr></thead><tbody id=sb>${S.map(s=>`<tr data-q="${h((s.u.name+' '+s.u.email).toLowerCase())}"><td>${h(s.u.name)}</td><td>${h(s.u.email)}</td><td><span class=tag style="--c:var(--mint)">${s.st}</span></td><td>${s.n}</td></tr>`).join('')}</tbody></table></div>`:'<p>No students yet. Students who request to join or register for your events will appear here.</p>'}</div>
<h2 class="strip torn" style="--c:var(--pink)">Your events</h2><div class=list>${ev.map(e=>`<div class=row><b>${h(e.title)}</b> ${h(e.date)}: ${e.cap-left(e)} of ${e.cap} seats taken <button class=ghost data-a=csv data-i=${e.id}>Download list (CSV)</button> <button class=ghost data-a=del data-c="Delete this event and its registrations?" data-i=${e.id}>Delete</button>${regList(e)}</div>`).join('')||'<p>No events yet. Create your first one above.</p>'}</div>`}
};
const dec=(i,s)=>{if(!own(cid()))return;const r=D.reqs.find(r=>r.uid==i&&r.cid==cid()&&r.st=='wait');if(r){r.st=s;toast(s=='ok'?'Request accepted':'Request declined')}};
const A={
join(i){if(!need())return;D.reqs.push({uid:D.me,cid:i,st:'wait'});toast('Request sent')},
reg(i){if(!need())return;const e=D.events.find(x=>x.id==i);if(left(e)<1)return;D.regs.push({id:uid(),uid:D.me,eid:i});toast('Registered')},
unreg(i){D.regs=D.regs.filter(r=>!(r.eid==i&&r.uid==D.me));toast('Registration cancelled')},
ok(i){dec(i,'ok')},no(i){dec(i,'no')},
del(i){const e=D.events.find(x=>x.id==i);if(!e||!own(e.cid))return;D.events=D.events.filter(x=>x!=e);D.regs=D.regs.filter(r=>r.eid!=i);toast('Event deleted')},
csv(i){const e=D.events.find(x=>x.id==i);if(!e||!own(e.cid))return 1;const rows=[['Name','Email','Ticket'],...D.regs.filter(r=>r.eid==i).map(r=>{const s=D.users.find(x=>x.id==r.uid);return[s.name,s.email,r.id.toUpperCase()]})],a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')],{type:'text/csv'}));a.download='registrations.csv';a.click();return 1},
csvs(){if(!own(cid()))return 1;const rows=[['Name','Email','Status','Events registered'],...studs(cid()).map(s=>[s.u.name,s.u.email,s.st,s.n])],a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')],{type:'text/csv'}));a.download='club-students.csv';a.click();return 1},
fav(i){D.fav=D.fav.includes(i)?D.fav.filter(x=>x!=i):[...D.fav,i];toast(D.fav.includes(i)?'Saved to your list':'Removed from saved')},qz(i){Q.a.push(...QZ[Q.s].o[i][1].split(','));Q.s++},qr(){Q={s:0,a:[]}},cat(i){CF=i;applyF();return 1},
menu(){const x=$('#nav'),o=x.classList.toggle('open');x.querySelector('.menu').setAttribute('aria-expanded',o);return 1},
out(){D.me=null;save();location='index.html';return 1}
};
const go=u=>location=u.role=='member'?'workspace.html':'student.html',done=t=>{save();toast(t);P.club()};
const F={
q(f){location='clubs.html?q='+encodeURIComponent(f.get('q'))},
flt(f){location='clubs.html?'+new URLSearchParams(f)},
login(f){const u=D.users.find(x=>x.email==f.get('email').toLowerCase()&&x.pw==btoa(f.get('pw')));if(!u)return toast('Email or password is incorrect');D.me=u.id;save();go(u)},
signup(f){const em=f.get('email').toLowerCase();if(D.users.some(x=>x.email==em))return toast('That email already has an account. Log in instead.');const role=f.get('role'),u={id:uid(),name:f.get('name'),email:em,pw:btoa(f.get('pw')),role,clubs:role=='member'?[f.get('club')]:[]};D.users.push(u);D.me=u.id;save();go(u)},
about(f){if(!own(cid()))return;D.clubs.find(c=>c.id==cid()).about=f.get('about');done('Profile saved')},
anf(f){if(!own(cid()))return;D.anns.unshift({id:uid(),cid:cid(),title:f.get('title'),date:new Date().toISOString().slice(0,10)});done('Announcement published')},
evf(f){if(!own(cid()))return;D.events.push({id:uid(),cid:cid(),title:f.get('title'),date:f.get('date'),venue:f.get('venue'),cap:Math.max(1,+f.get('cap'))});done('Event created')}
};
const burst=(x,y)=>{if(RM)return;for(let i=0;i<16;i++){const s=document.createElement('span');s.textContent=['🎉','✨','⭐','💜','🔥'][i%5];s.style.cssText=`position:fixed;left:${x}px;top:${y}px;font-size:${16+Math.random()*16}px;pointer-events:none;z-index:30`;document.body.append(s);const a=Math.random()*6.28,d=60+Math.random()*90;s.animate([{transform:'translate(-50%,-50%)',opacity:1},{transform:`translate(${Math.cos(a)*d-10}px,${Math.sin(a)*d+30}px) rotate(${Math.random()*360}deg)`,opacity:0}],{duration:900,easing:'cubic-bezier(.2,.8,.3,1)'}).onfinish=()=>s.remove()}};
document.addEventListener('input',e=>{if(e.target.closest('#flt'))applyF();if(e.target.id=='sf'){const v=e.target.value.toLowerCase();document.querySelectorAll('#sb tr').forEach(r=>r.hidden=!r.dataset.q.includes(v))}});
document.addEventListener('pointermove',e=>{if(RM||e.pointerType=='touch')return;const c=e.target.closest?.('.card');document.querySelectorAll('.card.t').forEach(x=>{if(x!==c){x.classList.remove('t');x.style.transform=''}});if(c){const r=c.getBoundingClientRect(),px=(e.clientX-r.left)/r.width-.5,py=(e.clientY-r.top)/r.height-.5;c.classList.add('t');c.style.transform=`perspective(700px) rotateX(${-py*7}deg) rotateY(${px*7}deg) translateY(-4px)`}
document.querySelectorAll('.bub').forEach(b=>{const s=+b.dataset.s;b.style.translate=`${(e.clientX/innerWidth-.5)*s}px ${(e.clientY/innerHeight-.5)*s}px`})});
document.addEventListener('keydown',e=>{if(e.key=='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){const i=$('.search input')||$('#flt input');if(i){e.preventDefault();i.focus()}}});
const WORDS=['code','build','design','lead','create','perform'];let wi=0;setInterval(()=>{const el=$('#tw');if(!el)return;wi=(wi+1)%WORDS.length;el.classList.remove('sw');void el.offsetWidth;el.textContent=WORDS[wi];el.classList.add('sw')},2000);
const U={home:'index.html',clubs:'clubs.html',events:'events.html',login:'login.html',me:'student.html',club:'workspace.html'};
let pg='home';
function render(){const p=document.body.dataset.p,qs=location.search.slice(1),u=me();pg=P[p]?p:'home';
const L=(k,t)=>`<a href="${U[k]}" ${pg==k?'class=on aria-current=page':''}>${t}</a>`;
$('#nav').innerHTML=`<a class=logo href="index.html">★ MCOE Pulse</a><button class=menu type=button aria-expanded=false data-a=menu>Menu</button><nav>${L('clubs','Clubs')}${L('events','Events')}${u?(u.role=='member'?L('club','Workspace'):'')+L('me','My space')+'<a href=# data-a=out>Log out</a>':L('login','Log in')}</nav>`;
P[pg](new URLSearchParams(qs||''))}
document.addEventListener('submit',e=>{const f=e.target;if(F[f.id]){e.preventDefault();F[f.id](new FormData(f))}});
document.addEventListener('change',e=>{if(e.target.id=='sw'){sessionStorage.cid=e.target.value;render()}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;e.preventDefault();if(b.dataset.c&&!confirm(b.dataset.c))return;const r=b.getBoundingClientRect(),a=b.dataset.a;if(A[a](b.dataset.i)!==1){save();render()}if((me()||a=='fav')&&['reg','join','ok','fav'].includes(a))burst(r.left+r.width/2,r.top+r.height/2)});
;
render();
